[tool.poetry]
name = "teko-ly-harjoitusty-"
version = "0.1.0"
description = "connect4_solver"
authors = ["John Smith <john@example.com>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
robotframework = "^7.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
